version: 2.1

orbs:
  python: circleci/python@0.2.1
  aws-cli: circleci/aws-cli@2.0
  serverless-framework: circleci/serverless-framework@1.0.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
  aws-check:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: aws s3 ls
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: cr-serverless-framework-orb
          org-name: circleci
      - run:
          command: serverless deploy -v
          name: deploy

workflows:
  main:
    jobs:
      - build-and-test
      - aws-check
      - deploy